### ISSUE TITLE
ScriptError: Exceeded maximum execution time

### ISSUE THREAD

**Issue by Biftekic** [IAmPicard/STTGoogleSheetsAddon#1]

**Comment by Biftekic** [comment]
I was running this script on google sheet and it is always exceeding time of 6 min it is allowed to run. It is always starting to populate excel table from start. I have more than 200 crew and it never achieve this number before this error happened. 
I think you can program script to start where it finished last time and continue from there. Than you will need option to repopulate everything or continue from the last time. 
Maybe you can solve it by checking everything and then writing it to table. I think this would make script faster by getValues instead od getValue. 
Sry for putting it here because I don't know how to do it myself.  Thank you and keep up the good work. :)

**Comment by IAmPicard** [comment]
I wasn't able to repro this. It shouldn't matter how many crew you have; the add-on will always load the full list (today that's 475), and fill in the details for the crew you own.

It never takes more than 1 - 1.5 minutes for me to fully populate the sheet.

I agree there's definitely room for improvement, though 😄 I do indeed populate the sheet one row at a time, I'll look into available options for bulk population of the list.

**Comment by Biftekic** [comment]
Sry I bothered you. I found what is problem.  Excel file STT crew lvl 100 stats i big and slow.  When you open new excel sheet it is populated in 10-20 sec. But with this file it is taking too long. Solution is not with your program but in excel. Keep a good job. Thank you.
